os: linux
dist: focal
language: generic
services:
  - docker
  - postgresql

before_install:
  - |
    # Install a more recent version than the default one
    export  DOCKER_COMPOSE_VERSION=1.29.2
    sudo rm /usr/local/bin/docker-compose
    curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    chmod +x docker-compose
    sudo mv docker-compose /usr/local/bin

before_script:
  - |
    # Travis context requires a specific database configuration
    psql -c 'create database extendeddoc;' -U postgres
    psql -c '\l' -U postgres

jobs:
  include:
    - stage: Building and running Spatial-Multimedia-DB container
      script:
        - docker build -t vcity:Spatial-Multimedia-DB Spatial-Multimedia-DB-context --build-arg POSTGRES_PORT=8995 --build-arg POSTGRES_PASSWORD="" --build-arg POSTGRES_HOST=localhost
        - docker run --rm --detach -t vcity:Spatial-Multimedia-DB
        - travis_wait 2 
        - docker stop $(docker ps -a -q --filter ancestor=vcity:Spatial-Multimedia-DB --format="{{.ID}}")
    - stage: Building and running docker-compose
      script:
        - |
          cd Example
          docker-compose build
          docker-compose up -d
          travis_wait 2
          docker-compose down
    - stage: "Markdown link checks"
      language: node_js
      node_js: 12
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=0
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi

