os: linux
dist: focal
language: generic
services:
  - docker

jobs:
  include:
    - stage: Building container
      script:
        - docker build -t vcity:Spatial-Multimedia-DB Spatial-Multimedia-DB-context
    - stage: Building docker-compose
      script:
        - docker-compose --version
        - docker-compose --help
        - docker-compose --project-directory Example build
    - stage: "Markdown link checks"
      language: node_js
      node_js: 4
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=0
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi

