os: linux
dist: focal
language: generic

addons:
  hosts:
    # Configure the "postgres" hostname in /etc/hosts and resolve it to
    # 127.0.0.1
    - postgres
  apt:
    packages:
    - net-tools    # For netstat
    
services:
  - docker
  # Note that it is NOT necessary to require the postgresql service
  # with a line of the form
  #   - postgresql
  # as explained by this post
  # https://stackoverflow.com/questions/61734368/postgresql-12-on-travis-ci-taking-5-minutes-to-startup#62037133

before_install:
  - |
    # Install a more recent version of DockerCompose than the default one
    export  DOCKER_COMPOSE_VERSION=1.29.2
    sudo rm /usr/local/bin/docker-compose
    curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    chmod +x docker-compose
    sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: Building and running Spatial-Multimedia-DB container
      script:
        ### Prepare the context of Spatial-Multimedia-DB.
        # Spatial-Multimedia-DB expects to have access to a postgreSQL
        # database. Prepare that context by launching that service
        #
        # The postgres container is configured to listen all addresses as
        # can be checked by # running the command
        #    docker run -i --rm postgres:9.6 cat /usr/share/postgresql/postgresql.conf.sample | grep listen_addresses
        # that returns
        #    listen_addresses = '*'
        # Refer to the "Database Configuration" of the docker documentation as
        # found at
        #    https://hub.docker.com/_/postgres
        #
        # We want the postgreSQL container to be configured with the "conninfo"
        # (psql terminology for connection info) that the Spatial-Multimedia-DB
        # we are testing will consume. We thus configure the postgreSQL to run
        # with the default values that Spatial-Multimedia-DB is expecting and
        # that are prescreibed wihtin its `.env` file (refer to
        # https://github.com/VCityTeam/Spatial-Multimedia-DB/blob/master/.env )
        - docker run --rm --detach -p 5432:5432 --user postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=extendeddoc -e POSTGRES_PASSWORD=password postgres:9.6
        # Wait a little bit for the container to spin off...
        - sleep 10
        # ...and make sure the container exposes the postgreSQL service on the
        # configured port (check for port 5432):
        - netstat -nlt
        # Check that the default database can indeed be reached (using the
        # "conninfo" string to designate the database) at the SQL level:
        - psql "host=postgres port=5432 dbname=extendeddoc user=postgres password=password" -c '\l'
        ### The context is now proprely setup. Proceed with building and
        # then running Spatial-Multimedia-DB container:
        - docker build -t vcity:Spatial-Multimedia-DB Spatial-Multimedia-DB-context
        - docker ps -a
        - docker run --rm --detach vcity:Spatial-Multimedia-DB
        - docker logs -f  $(docker ps -a -q --filter ancestor=vcity:Spatial-Multimedia-DB --format="{{.ID}}")
        - docker ps -a
        # Make sure the Spatial-Multimedia-DB container didn't immediatly die
        # at launchtime and display the logs it produced:
        - sleep 10
        - docker ps -a
        - docker ps -a -q --filter ancestor=vcity:Spatial-Multimedia-DB --format="{{.ID}}"
        - docker logs -f  $(docker ps -a -q --filter ancestor=vcity:Spatial-Multimedia-DB --format="{{.ID}}")
        - docker ps -a -q --filter ancestor=vcity:Spatial-Multimedia-DB --format="{{.ID}}"
        - docker stop $( docker ps -a -q --filter ancestor=vcity:Spatial-Multimedia-DB --format="{{.ID}}" )
        - docker ps -a -q --filter ancestor=vcity:Spatial-Multimedia-DB --format="{{.ID}}"
        # Eventually stop the context postgreSQL container
        - docker ps -a -q --filter ancestor=postgres:9.6 --format="{{.ID}}"
        - docker stop $(docker ps -a -q --filter ancestor=postgres:9.6 --format="{{.ID}}")
    - stage: Building and running docker-compose
      script:
        - |
          cd Example
          docker-compose build
          docker-compose up -d
          sleep 100
          docker-compose down
    - stage: "Markdown link checks"
      language: node_js
      node_js: 12
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=0
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi

